name: Python Playwright Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - '.github/workflows/python-tests.yml'
      - 'src/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - '.github/workflows/python-tests.yml'
      - 'src/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      working-directory: ./src
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      working-directory: ./src
      run: python -m playwright install --with-deps
    - name: Run your tests
      working-directory: ./src
      run: pytest --tracing=retain-on-failure
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: src/playwright-report/
        retention-days: 30